USE HospitalManagementSystem;

-- Partition the Appointment table by year
ALTER TABLE Appointment 
PARTITION BY RANGE (YEAR(date)) (
    PARTITION p_before_2023 VALUES LESS THAN (2023),
    PARTITION p_2023 VALUES LESS THAN (2024),
    PARTITION p_2024 VALUES LESS THAN (2025),
    PARTITION p_2025 VALUES LESS THAN (2026),
    PARTITION p_2026 VALUES LESS THAN (2027),
    PARTITION p_future VALUES LESS THAN MAXVALUE
);

-- Partition the Treatment table by year
ALTER TABLE Treatment 
PARTITION BY RANGE (YEAR(date)) (
    PARTITION p_before_2023 VALUES LESS THAN (2023),
    PARTITION p_2023 VALUES LESS THAN (2024),
    PARTITION p_2024 VALUES LESS THAN (2025),
    PARTITION p_2025 VALUES LESS THAN (2026),
    PARTITION p_2026 VALUES LESS THAN (2027),
    PARTITION p_future VALUES LESS THAN MAXVALUE
);

-- Partition the JobHistory table by year
ALTER TABLE JobHistory 
PARTITION BY RANGE (YEAR(change_date)) (
    PARTITION p_before_2023 VALUES LESS THAN (2023),
    PARTITION p_2023 VALUES LESS THAN (2024),
    PARTITION p_2024 VALUES LESS THAN (2025),
    PARTITION p_2025 VALUES LESS THAN (2026),
    PARTITION p_2026 VALUES LESS THAN (2027),
    PARTITION p_future VALUES LESS THAN MAXVALUE
);

-- Partition the Schedule table by week using date
ALTER TABLE Schedule 
PARTITION BY RANGE (TO_DAYS(date)) (
    PARTITION p_before_2023 VALUES LESS THAN (TO_DAYS('2023-01-01')),
    PARTITION p_2023 VALUES LESS THAN (TO_DAYS('2024-01-01')),
    PARTITION p_2024 VALUES LESS THAN (TO_DAYS('2025-01-01')),
    PARTITION p_2025 VALUES LESS THAN (TO_DAYS('2026-01-01')),
    PARTITION p_2026 VALUES LESS THAN (TO_DAYS('2027-01-01')),
    PARTITION p_future VALUES LESS THAN MAXVALUE
);

-- Partition the DocumentReference table by entity type
ALTER TABLE DocumentReference 
PARTITION BY LIST COLUMNS (entity_type) (
    PARTITION p_patient VALUES IN ('Patient'),
    PARTITION p_staff VALUES IN ('Staff'),
    PARTITION p_appointment VALUES IN ('Appointment')
);